# Site settings
title: LED mirror
header-img: img/home-bg.jpg
email: johan@fullscreen.nl
description: "2048 interactive pixels with Raspberry PI and Raspicam"
baseurl: "/led-mirror"
url: "http://www.fullscreen.nl"
github_username:  fullscreennl

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
